### ISSUE TITLE
[BUG] Displaying skins in the game

### ISSUE THREAD

**Issue by OhotnikNaSov** [GHAuth-Team/ghauth#34]
Hello! I apologize for so many problems and questions, but maybe you know what this is connected with? All certificates are connected, but the skin does not load, I tried messing around with skinDomains, but both on localhost and on VDS, but the result is 0
-----------------------------------------------------------------------------------------------------------------------------------------------

[authlib-injector] [INFO] Transformed [com.mojang.authlib.properties.Property] with [Yggdrasil Public Key Transformer]
[01:15:34] [Worker-Main-17/INFO]: [STDOUT]: /textures/eed1c84c1445ffd65b198e36f06855d20b3dfc04996d1e346cfbc8b808138004
[01:15:34] [Worker-Main-17/WARN]: Worker-Main-17 died
java.lang.NullPointerException: null
        at moe.yushi.authlibinjector.transform.support.SkinWhitelistTransformUnit.domainMatches(SkinWhitelistTransformUnit.java:43) ~[authlib-injector.jar:1.2.3]
        at moe.yushi.authlibinjector.transform.support.SkinWhitelistTransformUnit.isWhitelistedDomain(SkinWhitelistTransformUnit.java:75) ~[authlib-injector.jar:1.2.3]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.isWhitelistedDomain(YggdrasilMinecraftSessionService.java) ~[authlib-2.1.28.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:160) ~[authlib-2.1.28.jar:?]
        at eks.a(SourceFile:99) ~[1.16.5.jar:?]
        at eks$$Lambda$4820/249569791.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[01:15:34] [Worker-Main-17/ERROR]: Caught exception in thread Thread[Worker-Main-17,5,main]
java.lang.NullPointerException: null
        at moe.yushi.authlibinjector.transform.support.SkinWhitelistTransformUnit.domainMatches(SkinWhitelistTransformUnit.java:43) ~[authlib-injector.jar:1.2.3]
        at moe.yushi.authlibinjector.transform.support.SkinWhitelistTransformUnit.isWhitelistedDomain(SkinWhitelistTransformUnit.java:75) ~[authlib-injector.jar:1.2.3]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.isWhitelistedDomain(YggdrasilMinecraftSessionService.java) ~[authlib-2.1.28.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:160) ~[authlib-2.1.28.jar:?]
        at eks.a(SourceFile:99) ~[1.16.5.jar:?]
        at eks$$Lambda$4820/249569791.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51]
       
-----------------------------------------------------------------------------------------------------------------------------------------------
ServerLog
-----------------------------------------------------------------------------------------------------------------------------------------------
<-- GET /api/yggdrasil/sessionserver/session/minecraft/profile/e334dee0738d11eea68da7bd85537beb
--> GET /api/yggdrasil/sessionserver/session/minecraft/profile/e334dee0738d11eea68da7bd85537beb 200 9ms 1.09kb

**Comment by daidr** [comment]
I guess there might be a problem with the configuration of skinDomains?
You can open https://auth.daidr.me/api/yggdrasil for reference.
Normally, the skinDomains in metadata should be set to the current authentication service domain.

**Comment by OhotnikNaSov** [comment]
Hello, I changed the Dovins skin to this -
    skinDomains:
        - http://45.**.***.231:3000
        - http://45.**.***.231
        - http://45.**.***.231:3000/api/yggdrasil

And it worked, but everything works when I went through a regular bat file with the old data. Everything was fine from the old batch file, but now when I issue an auth token and so on, an error comes out!
[18:13:17] [Worker-Main-13/INFO]: [STDOUT]: http://45.**.***.231:3000/textures/463e31f9ec697e12a5ea296573204ed2c761556ede6cc29f8fe3639764dc738c
[18:13:17] [Worker-Main-13/ERROR]: Textures payload has been tampered with (non-whitelisted domain)

I tried replacing the parameter (-Dauthlibinjector.yggdrasil.prefetched=eyJtZXRhIjp7....) from the old batch file with the new one and it worked (True, this will only work on only one old account)

**Comment by daidr** [comment]
In fact, you don't need to add a protocol prefix for skinDomains. That is, you should remove "http://".

**Comment by OhotnikNaSov** [comment]
If I remove it, I get a URL error

**Comment by OhotnikNaSov** [comment]
Thanks for the help! The problem was solved by connecting the domain
